name: Coder Workspace Automation

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main  # Automatic trigger on push to the main branch

jobs:
  create-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Coder CLI
        run: |
          curl -L https://coder.com/install.sh | sh
          echo "$HOME/.coder/bin" >> $GITHUB_PATH

      - name: Authenticate with Coder
        env:
          CODER_URL: http://194.233.74.174/
          CODER_TOKEN: ${{ secrets.CODER_TOKEN }}
        run: |
          coder login $CODER_URL --token=$CODER_TOKEN

      - name: Create Coder Workspace
        run: |
          coder create my-workspace \
            --template="devcontainer-docker" \
            --parameter repo="https://github.com/microsoft/vscode"

      - name: Wait for Workspace to Be Ready
        run: |
          while true; do
            status=$(coder show my-workspace --output json | jq -r '.latest_build.status')
            if [ "$status" == "success" ]; then
              break
            fi
            echo "Waiting for workspace to be ready..."
            sleep 10
          done

      - name: Get Workspace IP
        id: workspace-ip
        run: |
          workspace_ip=$(coder show my-workspace --output json | jq -r '.latest_build.resources[0].agents[0].ip')
          echo "Workspace IP: $workspace_ip"
          echo "workspace_ip=$workspace_ip" >> $GITHUB_OUTPUT

      - name: Run Commands in Workspace
        run: |
          ssh -i ${{ secrets.SSH_KEY_PATH }} root@${{ steps.workspace-ip.outputs.workspace_ip }} "
            sudo apt update && sudo apt install python3 python3-venv python3-pip -y &&
            python3 -m venv myenv &&
            source myenv/bin/activate
          "

      - name: Delete Workspace
        if: always()  # Run even if previous steps fail
        run: |
          coder delete my-workspace --yes
